# Site settings
title: Weili Cao
email: w2cao@ucsd.edu
description: >
  Weili Cao's personal academic website, focusing on NLP, ML, and biomedical applications.
baseurl: ""
url: "https://weilicao.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 
